mappings:
  GridFieldAddByDBField: Restruct\Silverstripe\FilterableArchive\GridFieldAddByDBField
  FilterCategory: Restruct\Silverstripe\FilterableArchive\FilterCategory
  FilterTag: Restruct\Silverstripe\FilterableArchive\FilterTag
  FilterableArchiveItemExtension: Restruct\Silverstripe\FilterableArchive\FilterableArchiveItemExtension
  FilterableArchiveHolder_ControllerExtension: Restruct\Silverstripe\FilterableArchive\FilterableArchiveHolder_ControllerExtension
  FilterableArchiveHolderExtension: Restruct\Silverstripe\FilterableArchive\FilterableArchiveHolderExtension
